//! Nested bit-plane packing — the real storage format Phase 1 only simulated.
//!
//! Contract with the Python golden model (`myelin/bitplane.py`):
//! `pack` followed by `dequantize` must reproduce `quantize_rows(w, bits)`
//! **bit-exactly** for all finite inputs. This holds because every step is an
//! exact IEEE-754 operation: `w / scale` matches torch's fp32 division, the
//! plane decision compares the fixed unit value against a running
//! reconstruction whose partial sums are odd multiples of 2^-i (<= 8 mantissa
//! bits, always exact), the reconstructed unit value is a dyadic rational
//! exactly representable in f32, and the final `unit * scale` performs the
//! single identical rounding both sides share.
//!
//! CAUTION: the naive residual form (`r -= b * 2^-i`) is NOT exact — within
//! ~16 ulps below a grid boundary the subtraction lands on a round-half-even
//! midpoint, collapses onto the grid, and flips the tie to the wrong level
//! (321 mismatching (value, k) pairs over all f32 in [-1,1], k=1..8). Both
//! this crate and the Python `plane_decompose` use the running-sum form.
//!
//! Non-finite weights are rejected with an error: torch propagates NaN
//! through `quantize_rows` while `f32::max` would ignore it, so packing them
//! could only ever produce silent divergence.
//!
//! `tests/golden.rs` pins the contract against vectors generated by the
//! Python side, including boundary-ulp ladders.

/// Maximum planes per channel; mirrors `max_bits` in the Python allocator.
pub const MAX_BITS: usize = 8;

/// 2^-(i) for i = 0..=8 as exact f32 literals (avoid `powi`, which the std
/// docs allow to be inexact).
pub(crate) const STEP: [f32; MAX_BITS + 1] = [
    1.0, 0.5, 0.25, 0.125, 0.0625, 0.03125, 0.015625, 0.0078125, 0.00390625,
];

/// Same eps as Python `quantize_rows` (clamp_min on the absmax scale).
pub const SCALE_EPS: f32 = 1e-12;

/// A weight matrix stored as per-row scale + variable-count sign planes.
///
/// Plane bit semantics: bit set = +1, bit clear = -1 (sign convention
/// `sign(0) := +1`, matching `plane_decompose`). Column `j` of a plane lives
/// in word `j / 64`, bit `j % 64` (LSB-first). Words beyond `cols` are
/// zero-padded; padding never contributes because summations only visit set
/// bits for +1 mass and subtract the true column total.
///
/// Layout: for each row, its `bits[row]` planes are stored contiguously
/// (`words_per_plane` words each), rows concatenated in order. Reading a row
/// therefore streams exactly `bits[row] * words_per_plane * 8` bytes — the
/// "pay for what you read" property the whole project is about.
#[derive(Clone, Debug)]
pub struct PackedMatrix {
    pub rows: usize,
    pub cols: usize,
    pub scales: Vec<f32>,
    pub bits: Vec<u8>,
    pub words_per_plane: usize,
    /// word offset of each row's first plane, plus a final total sentinel
    pub row_offsets: Vec<usize>,
    pub planes: Vec<u64>,
}

impl PackedMatrix {
    /// Bytes of plane data streamed by one full matrix-vector product.
    pub fn plane_bytes(&self) -> usize {
        self.planes.len() * 8
    }

    /// Mean bits per weight under the current allocation.
    pub fn mean_bits(&self) -> f64 {
        if self.rows == 0 {
            return 0.0;
        }
        self.bits.iter().map(|&b| b as f64).sum::<f64>() / self.rows as f64
    }
}

/// Quantize + pack a row-major f32 matrix into bit planes.
///
/// `bits[r]` must be in `1..=MAX_BITS`.
pub fn pack(weights: &[f32], rows: usize, cols: usize, bits: &[u8]) -> Result<PackedMatrix, String> {
    // Checked arithmetic throughout: `rows * cols` wraps silently in release
    // builds, so e.g. (2, 2^63) would pass a naive length check with empty
    // inputs and then attempt an astronomical plane allocation — and Rust's
    // OOM handler aborts the whole host process (observed as a SIGABRT taking
    // Python down). After these checks every allocation below is bounded by
    // O(weights.len() + bits.len()).
    let expected = rows
        .checked_mul(cols)
        .ok_or_else(|| format!("rows*cols overflows usize: {rows}*{cols}"))?;
    if weights.len() != expected {
        return Err(format!(
            "weights length {} != rows*cols {}",
            weights.len(),
            expected
        ));
    }
    if bits.len() != rows {
        return Err(format!("bits length {} != rows {}", bits.len(), rows));
    }
    if let Some(&b) = bits.iter().find(|&&b| b == 0 || b as usize > MAX_BITS) {
        return Err(format!("bits value {b} outside 1..={MAX_BITS}"));
    }
    if let Some(pos) = weights.iter().position(|v| !v.is_finite()) {
        return Err(format!(
            "non-finite weight {} at index {pos}: the golden model (torch) \
             propagates NaN where f32::max ignores it, so packing would \
             silently diverge",
            weights[pos]
        ));
    }

    let words_per_plane = cols.div_ceil(64);
    if rows == 0 {
        return Ok(PackedMatrix {
            rows: 0,
            cols,
            scales: Vec::new(),
            bits: Vec::new(),
            words_per_plane,
            row_offsets: vec![0],
            planes: Vec::new(),
        });
    }

    let mut row_offsets = Vec::with_capacity(rows + 1);
    let mut total_words = 0usize;
    for &b in bits {
        row_offsets.push(total_words);
        total_words = (b as usize)
            .checked_mul(words_per_plane)
            .and_then(|w| total_words.checked_add(w))
            .ok_or_else(|| "plane storage size overflows usize".to_string())?;
    }
    row_offsets.push(total_words);

    let mut scales = Vec::with_capacity(rows);
    let mut planes = vec![0u64; total_words];
    let mut unit = vec![0f32; cols];
    let mut recon = vec![0f32; cols];

    for r in 0..rows {
        let row = &weights[r * cols..(r + 1) * cols];
        let scale = row.iter().fold(0f32, |m, &v| m.max(v.abs())).max(SCALE_EPS);
        scales.push(scale);
        for (u, &v) in unit.iter_mut().zip(row) {
            *u = v / scale;
        }
        recon.fill(0.0);
        let base = row_offsets[r];
        for i in 0..bits[r] as usize {
            let plane = &mut planes[base + i * words_per_plane..base + (i + 1) * words_per_plane];
            for j in 0..cols {
                // Compare the FIXED unit value against the running
                // reconstruction — exact, unlike mutating a residual (see
                // module docs). sign convention: tie (u == recon, incl.
                // -0.0 >= 0.0) resolves to +1, matching torch.where(r >= 0).
                if unit[j] >= recon[j] {
                    plane[j / 64] |= 1u64 << (j % 64);
                    recon[j] += STEP[i + 1];
                } else {
                    recon[j] -= STEP[i + 1];
                }
            }
        }
    }

    Ok(PackedMatrix {
        rows,
        cols,
        scales,
        bits: bits.to_vec(),
        words_per_plane,
        row_offsets,
        planes,
    })
}

/// Reconstruct the quantized f32 matrix (row-major). Bit-exactly equal to the
/// Python `quantize_rows(w, bits)` output for the packed weights.
pub fn dequantize(m: &PackedMatrix) -> Vec<f32> {
    let mut out = vec![0f32; m.rows * m.cols];
    for r in 0..m.rows {
        let base = m.row_offsets[r];
        let row = &mut out[r * m.cols..(r + 1) * m.cols];
        for i in 0..m.bits[r] as usize {
            let plane = &m.planes[base + i * m.words_per_plane..base + (i + 1) * m.words_per_plane];
            let step = STEP[i + 1];
            for (j, v) in row.iter_mut().enumerate() {
                if plane[j / 64] >> (j % 64) & 1 == 1 {
                    // exact: accumulating distinct powers of two
                    *v += step;
                } else {
                    *v -= step;
                }
            }
        }
        let scale = m.scales[r];
        for v in row.iter_mut() {
            *v *= scale;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Deterministic pseudo-random f32s without a rand dependency.
    pub(crate) fn lcg_f32(state: &mut u64) -> f32 {
        *state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        // top 24 bits -> [-1, 1)
        ((*state >> 40) as f32 / (1u32 << 23) as f32) - 1.0
    }

    fn random_matrix(rows: usize, cols: usize, seed: u64) -> (Vec<f32>, Vec<u8>) {
        let mut s = seed;
        let w: Vec<f32> = (0..rows * cols).map(|_| lcg_f32(&mut s) * 3.0).collect();
        let bits: Vec<u8> = (0..rows).map(|r| (r % MAX_BITS) as u8 + 1).collect();
        (w, bits)
    }

    #[test]
    fn roundtrip_error_bound() {
        let (w, bits) = random_matrix(16, 100, 7);
        let m = pack(&w, 16, 100, &bits).unwrap();
        let q = dequantize(&m);
        for r in 0..16 {
            let scale = m.scales[r];
            let bound = scale * STEP[bits[r] as usize] + 1e-6;
            for j in 0..100 {
                let err = (w[r * 100 + j] - q[r * 100 + j]).abs();
                assert!(err <= bound, "row {r} col {j}: err {err} > bound {bound}");
            }
        }
    }

    #[test]
    fn nesting_prefix_planes_match_lower_bitwidth() {
        // reading fewer planes of a high-bit row == packing at the lower width
        let (w, _) = random_matrix(4, 64, 11);
        let full = pack(&w, 4, 64, &[8, 8, 8, 8]).unwrap();
        for k in 1..=8u8 {
            let low = pack(&w, 4, 64, &[k; 4]).unwrap();
            let mut truncated = full.clone();
            truncated.bits = vec![k; 4];
            // rebuild offsets/planes for the prefix
            let wpp = truncated.words_per_plane;
            let mut planes = Vec::new();
            let mut offsets = Vec::new();
            for r in 0..4 {
                offsets.push(planes.len());
                let base = full.row_offsets[r];
                planes.extend_from_slice(&full.planes[base..base + k as usize * wpp]);
            }
            offsets.push(planes.len());
            truncated.planes = planes;
            truncated.row_offsets = offsets;
            assert_eq!(dequantize(&truncated), dequantize(&low), "k={k}");
        }
    }

    #[test]
    fn zero_row_is_safe() {
        let w = vec![0f32; 32];
        let m = pack(&w, 1, 32, &[4]).unwrap();
        let q = dequantize(&m);
        assert!(q.iter().all(|v| v.is_finite()));
        assert!(q.iter().all(|v| v.abs() <= SCALE_EPS));
    }

    #[test]
    fn rejects_bad_bits() {
        let w = vec![0f32; 4];
        assert!(pack(&w, 1, 4, &[0]).is_err());
        assert!(pack(&w, 1, 4, &[9]).is_err());
        assert!(pack(&w, 2, 2, &[1]).is_err());
    }

    #[test]
    fn reviewer_counterexample_bit_exact() {
        // u = 0.25 - 2^-26 (0x3E7FFFFF): the residual-form decomposition
        // yielded 0.375; the closed form / running-sum form yield 0.125
        let u = f32::from_bits(0x3E7FFFFF);
        let m = pack(&[u, 1.0], 1, 2, &[3]).unwrap();
        let q = dequantize(&m);
        assert_eq!(q[0].to_bits(), 0.125f32.to_bits());
        assert_eq!(q[1].to_bits(), 0.875f32.to_bits());
    }

    #[test]
    fn boundary_ulp_ladders_match_closed_form() {
        // sweep 16 ulps below/above every grid boundary for every k: the
        // reconstruction must equal the mid-rise closed form computed here
        for k in 1..=MAX_BITS {
            let delta = STEP[k] * 2.0; // 2^(1-k)
            let mut xs: Vec<f32> = Vec::new();
            let half = 1i32 << (k - 1);
            for m in -half..=half {
                let g = m as f32 * delta;
                xs.push(g.clamp(-1.0, 1.0));
                let mut lo = g;
                let mut hi = g;
                for _ in 0..16 {
                    lo = f32::from_bits(next_toward(lo, -2.0));
                    hi = f32::from_bits(next_toward(hi, 2.0));
                    xs.push(lo.clamp(-1.0, 1.0));
                    xs.push(hi.clamp(-1.0, 1.0));
                }
            }
            let bits = vec![k as u8; 1];
            for &x in &xs {
                // scale 1.0 exactly: add a sentinel 1.0 so absmax == 1.0
                let m = pack(&[x, 1.0], 1, 2, &bits).unwrap();
                let q = dequantize(&m)[0];
                let closed = closed_form_unit(x, k);
                assert_eq!(
                    q.to_bits(),
                    closed.to_bits(),
                    "k={k} x={x} ({:08x}): got {q} want {closed}",
                    x.to_bits()
                );
            }
        }
    }

    /// mid-rise closed form on [-1,1], mirroring Python quantize_unit
    fn closed_form_unit(x: f32, k: usize) -> f32 {
        let delta = STEP[k] * 2.0;
        let q = delta * ((x / delta).floor() + 0.5);
        let hi = 1.0 - 0.5 * delta;
        q.clamp(-hi, hi)
    }

    /// nextafter for f32 (std's f32::next_up/down stabilized late; do it raw)
    fn next_toward(x: f32, toward: f32) -> u32 {
        if x == toward {
            return x.to_bits();
        }
        let bits = x.to_bits();
        if x == 0.0 {
            return if toward > 0.0 { 1 } else { 0x8000_0001 };
        }
        if (x > 0.0) == (toward > x) {
            bits + 1
        } else {
            bits - 1
        }
    }

    #[test]
    fn rejects_non_finite_weights() {
        assert!(pack(&[f32::NAN, 1.0], 1, 2, &[3]).is_err());
        assert!(pack(&[f32::INFINITY, 1.0], 1, 2, &[3]).is_err());
        assert!(pack(&[1.0, f32::NEG_INFINITY], 1, 2, &[3]).is_err());
    }

    #[test]
    fn overflowing_dims_error_instead_of_aborting() {
        // regression: 2 * 2^63 wraps to 0 == len([]) with naive arithmetic,
        // then the plane allocation aborts the process via the OOM handler
        let huge = 1usize << 63;
        assert!(pack(&[], 2, huge, &[4, 4]).is_err());
        assert!(pack(&[], huge, 2, &[]).is_err());
        assert!(pack(&[], usize::MAX, usize::MAX, &[]).is_err());
    }

    #[test]
    fn empty_matrix_is_valid() {
        let m = pack(&[], 0, 128, &[]).unwrap();
        assert_eq!(m.rows, 0);
        assert_eq!(m.plane_bytes(), 0);
        assert!(dequantize(&m).is_empty());
    }
}
