//! Golden-model contract tests against vectors generated by the Python side.
//!
//! Regenerate with: `.venv/bin/python scripts/gen_golden.py` (repo root).
//!
//! Contract:
//! * pack -> dequantize == Python `quantize_rows(w, bits)` BIT-EXACTLY
//!   (f32 bit patterns compared, not approximate equality)
//! * matvec == f64 reference dot of the quantized weights, within 1e-5 rel.

use serde::Deserialize;

use myelin_kernel::{dequantize, matvec, pack};

#[derive(Deserialize)]
struct Case {
    name: String,
    rows: usize,
    cols: usize,
    bits: Vec<u8>,
    weights: Vec<f32>,
    x: Vec<f32>,
    expected_q: Vec<f32>,
    expected_y: Vec<f64>,
}

#[derive(Deserialize)]
struct Golden {
    cases: Vec<Case>,
}

fn load() -> Golden {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden.json");
    let text = std::fs::read_to_string(path)
        .expect("tests/golden.json missing — run scripts/gen_golden.py first");
    serde_json::from_str(&text).expect("golden.json parse error")
}

#[test]
fn dequantize_is_bit_exact_vs_python() {
    let golden = load();
    assert!(!golden.cases.is_empty());
    for case in &golden.cases {
        let m = pack(&case.weights, case.rows, case.cols, &case.bits).unwrap();
        let q = dequantize(&m);
        assert_eq!(q.len(), case.expected_q.len(), "{}", case.name);
        for (idx, (got, want)) in q.iter().zip(&case.expected_q).enumerate() {
            assert_eq!(
                got.to_bits(),
                want.to_bits(),
                "case {} idx {}: got {} want {} (bit patterns {:08x} vs {:08x})",
                case.name,
                idx,
                got,
                want,
                got.to_bits(),
                want.to_bits()
            );
        }
    }
}

#[test]
fn matvec_matches_f64_reference() {
    let golden = load();
    for case in &golden.cases {
        let m = pack(&case.weights, case.rows, case.cols, &case.bits).unwrap();
        let y = matvec(&m, &case.x);
        for (r, (&got, &want)) in y.iter().zip(&case.expected_y).enumerate() {
            let tol = 1e-5 * want.abs().max(1.0);
            assert!(
                (got as f64 - want).abs() <= tol,
                "case {} row {}: got {} want {}",
                case.name,
                r,
                got,
                want
            );
        }
    }
}
